cache:
  directories:
    - _cache/rebar3

install:
  - wget https://s3.amazonaws.com/travis-otp-releases/binaries/$(lsb_release -is | tr "A-Z" "a-z")/$(lsb_release -rs)/$(uname -m)/erlang-18.2-nonroot.tar.bz2
  - mkdir -p ~/otp && tar -xf erlang-18.2-nonroot.tar.bz2 -C ~/otp/
  - mkdir -p ~/.kerl
  - source $HOME/otp/18.2/activate
  - >
    if [ ! -f _cache/rebar3/rebar3 ]; then
      mkdir -p _cache/rebar3
      git clone https://github.com/erlang/rebar3 _build/rebar3
      (cd _build/rebar3 && ./bootstrap)
      ls _build/rebar3
      cp _build/rebar3/rebar3 _cache/rebar3/
    fi

script: "make tests REBAR=_cache/rebar3/rebar3"
